### ISSUE TITLE
ssu-bills doesn't show actual bill count

### ISSUE THREAD

**Issue by keo** [lamassu/lamassu-scripts#49]
`ssu-bills` used to show actual bill count, now it doesn't. It would be really good to get that feature back.

Running `ssu-bills` alone results in an error:

```
$ ssu-bills
Reset bill counts for dispenser.
Usage: ssu-bills [<machine name>] [<top count> <bottom count>]

Example: ssu-bills fancy-horse 200 50
Resets top cartridge to 200 bills, bottom cartridge to 50 bills.
If you're only operating one machine, machine name is optional.

Current counts:
No data returned from the query.
QueryResultError: 0
    at QueryResultError.Error (<anonymous>)
    at new QueryResultError (/usr/local/lib/node_modules/lamassu-scripts/node_modules/pg-promise/lib/errors/queryResult.js:125:22)
    at null.<anonymous> (/usr/local/lib/node_modules/lamassu-scripts/node_modules/pg-promise/lib/query.js:172:41)
    at Query.handleReadyForQuery (/usr/local/lib/node_modules/lamassu-scripts/node_modules/pg-promise/node_modules/pg/lib/query.js:106:10)
    at null.<anonymous> (/usr/local/lib/node_modules/lamassu-scripts/node_modules/pg-promise/node_modules/pg/lib/client.js:163:19)
    at emit (events.js:117:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/lamassu-scripts/node_modules/pg-promise/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
```

Running it with the machine name it doesn't return anything:

```
# ssu-bills machine-name
Reset bill counts for dispenser.
Usage: ssu-bills [<machine name>] [<top count> <bottom count>]

Example: ssu-bills fancy-horse 200 50
Resets top cartridge to 200 bills, bottom cartridge to 50 bills.
If you're only operating one machine, machine name is optional.

You have multiple machines, please supply a machine name.
```

It also tells me that I have multiple machine and I should mention a machine name (even though I mentioned it).

**Comment by naconner** [comment]
Thanks for the findings, @keo. Could you confirm your versions with `npm -g ls lamassu-config`?

Also, were there any changes made on the server leading up to this error?

**Comment by vitaly-t** [comment]
Just so, technically, this is the result of calling either `db.one` or `db.many` that require data to be returned by the query, but the query returns nothing :wink:

**Comment by keo** [comment]
@naconner we're on `lamassu-scripts@0.2.33`

**Comment by ergofobe** [comment]
I'm reconfirming this issue with `lamassu-scripts@0.2.36` & `lamassu-config@0.4.4  (git://github.com/lamassu/lamassu-config.git#eec24cc97272bbcfd13877fa2085eeb817e7ae7c)`
